language: java

jdk:
  - oraclejdk8

services:
  - mysql

sudo: false

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

install:
  - mkdir -p download
  - src/test/bash/create_certificates.sh
  - src/test/bash/install_vault.sh
  - src/test/bash/install_consul.sh
  - src/test/bash/local_run_vault.sh &
  - src/test/bash/local_run_consul.sh &
  - mysql -e "CREATE USER 'spring' IDENTIFIED by 'vault';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'spring'@'%' WITH GRANT OPTION;";
  - source src/test/bash/env.sh && src/test/bash/setup_examples.sh

script: ./mvnw clean verify -Pci

after_script:
  - pkill vault
  - pkill consul

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'
    - 'download'
