language: java

services:
  - mysql

sudo: false

matrix:
  include:
    - jdk: oraclejdk7
      env:
        - PROFILE=ci
    - jdk: oraclejdk8
      env:
        - PROFILE=ci
    - jdk: oraclejdk8
      env:
        - PROFILE=spring5-next

install:
  - mkdir -p download
  - src/test/bash/create_certificates.sh
  - src/test/bash/install_vault.sh
  - src/test/bash/local_run_vault.sh &
  - mysql -e "CREATE USER 'spring' IDENTIFIED by 'vault';"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'spring'@'%' WITH GRANT OPTION;";
  - source src/test/bash/env.sh && src/test/bash/setup_examples.sh

script: mvn clean verify -P${PROFILE}

after_script:
  - pkill vault

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'download'
